apiVersion: apps/v1
kind: Deployment
metadata:
  name: source-ip-server-simple-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: source-ip-server-simple
  template:
    metadata:
      labels:
        app: source-ip-server-simple
    spec:
      containers:
      - name: source-ip-server-simple
        image: testgabacr.azurecr.io/testpod:latest
        ports:
        - containerPort: 12345
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"

